import sys
from types import ModuleType
from pathlib import Path
from html import escape
import importlib.util

import matplotlib
import pytest

matplotlib.use("Agg")


_DUNESTYLE_SOURCE = "real package"


def _ensure_dunestyle_stub():
    global _DUNESTYLE_SOURCE

    if importlib.util.find_spec("dunestyle.matplotlib") is not None:
        _DUNESTYLE_SOURCE = "real package"
        return

    dunestyle = ModuleType("dunestyle")
    matplotlib_mod = ModuleType("dunestyle.matplotlib")
    dunestyle.matplotlib = matplotlib_mod

    sys.modules.setdefault("dunestyle", dunestyle)
    sys.modules.setdefault("dunestyle.matplotlib", matplotlib_mod)
    _DUNESTYLE_SOURCE = "test stub fallback"


_ensure_dunestyle_stub()


@pytest.fixture(scope="session")
def plot_artifact_dir():
    output_dir = Path(__file__).resolve().parent / "output" / "plots"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def pytest_sessionfinish(session, exitstatus):
    plots_dir = Path(__file__).resolve().parent / "output" / "plots"
    if not plots_dir.exists():
        return

    image_files = sorted(plots_dir.glob("*.png"))
    html_path = plots_dir.parent / "index.html"
    status_class = "status-real" if _DUNESTYLE_SOURCE == "real package" else "status-fallback"
    status_text = (
        "Rendered with the real dunestyle package installed in the environment."
        if _DUNESTYLE_SOURCE == "real package"
        else "Rendered with the test stub fallback because dunestyle was not installed."
    )

    cards = []
    for image_file in image_files:
        name = image_file.name
        rel_path = f"plots/{name}"
        cards.append(
            f"""
            <article class="card">
              <h2>{escape(name)}</h2>
              <a href="{escape(rel_path)}"><img src="{escape(rel_path)}" alt="{escape(name)}"></a>
            </article>
            """
        )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pytest Plot Artifacts</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f5f1e8;
      --panel: #fffdf8;
      --ink: #1f2a33;
      --line: #d8ccb8;
      --accent: #0f766e;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Georgia, "Times New Roman", serif;
      background: linear-gradient(180deg, #efe7d8 0%, var(--bg) 100%);
      color: var(--ink);
    }}
    main {{
      max-width: 1200px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 2rem;
    }}
    p {{
      margin: 0 0 24px;
      color: #48545e;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 18px;
    }}
    .status {{
      margin: 0 0 24px;
      padding: 12px 14px;
      border-radius: 12px;
      border: 1px solid var(--line);
      background: var(--panel);
      font-size: 0.98rem;
    }}
    .status-real {{
      border-color: #7fb7ad;
      background: #eef8f5;
    }}
    .status-fallback {{
      border-color: #d7b46a;
      background: #fff5dc;
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 14px;
      padding: 14px;
      box-shadow: 0 10px 30px rgba(31, 42, 51, 0.08);
    }}
    .card h2 {{
      margin: 0 0 10px;
      font-size: 1rem;
      color: var(--accent);
    }}
    img {{
      display: block;
      width: 100%;
      height: auto;
      border-radius: 10px;
      border: 1px solid var(--line);
      background: white;
    }}
  </style>
</head>
<body>
  <main>
    <h1>Pytest Plot Artifacts</h1>
    <p>Visual summaries generated by the plotting-script tests.</p>
    <p class="status {status_class}"><strong>DUNE style status:</strong> {escape(status_text)}</p>
    <section class="grid">
      {''.join(cards) if cards else '<p>No plot artifacts were generated.</p>'}
    </section>
  </main>
</body>
</html>
"""
    html_path.write_text(html, encoding="utf-8")
